services:
  evolution-api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:v2.3.1
    depends_on:
      - redis
    restart: no
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=xwEDTCrl859jgllKO0bvjKBmbfYbw77k
      - CONFIG_SESSION_PHONE_VERSION=2.3000.1020885143
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/postgres
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=true
      - CACHE_LOCAL_ENABLED=false
    volumes:
      - evolution_instances:/evolution/instances
    networks:
    - evolution-net

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - evolution-net

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - evolution-net

volumes:
  evolution_instances:
  postgres_data:

networks:
  evolution-net:
    driver: bridge